steps:
  # Install dependencies
  - name: python
    entrypoint: pipenv
    args: ["shelll"]

  - name: python
    entrypoint: pipenv
    args: ["install"]
  # Run unit tests
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "--junitxml=${SHORT_SHA}_test_log.xml"] 

# Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
         'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/gestor_entrenamientos:${SHORT_SHA}', '.']

# Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/gestor_entrenamientos:${SHORT_SHA}']

# Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'gestor_entrenamientos-${SHORT_SHA}',
         '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/gestor_entrenamientos:${SHORT_SHA}',
         '--region', 'us-central1', '--platform', 'managed',
         '--allow-unauthenticated']  