version: '3'
networks:
  sportapp:
    driver: bridge

services: 
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - sportapp
    environment:
      POSTGRES_DB: sportapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5

  # Servicios de sportapp
  gestorentrenamientos:
    container_name: gentrenamientos
    hostname: gentrenamientos
    restart: on-failure
    build:
      context: .
      dockerfile: ./gestor_entrenamientos/Dockerfile
    environment:
      - GESTORENTRENAMIENTOS_ADDRESS=gentrenamientos
      - PATH_PUBSUB_KEY=proyecto1-experimentos-a4f693fafcec.json
      - PATH_TOPIC=projects/proyecto1-experimentos/topics/notifications
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sportapp
      - APP_PORT=3000
    ports:
      - "5000:5000"
    networks:
      - sportapp
    depends_on:
      postgres:
        condition: service_healthy