version: '3'
networks:
  sportapp:
    driver: bridge

services: 
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - sportapp
    environment:
      POSTGRES_DB: sportapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5

  gestorusuarios:
    container_name: gusuarios
    hostname: gusuarios
    restart: on-failure
    build:
      context: ./gestor_usuarios
      dockerfile: Dockerfile
      target: prod
    environment:
      - JWT_SECRET_KEY=JwBGj2B4XFAKhYmn8Pgk0vH2w7UvgYfXAJ32e5rs8vI=
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sportapp
      - APP_PORT=3000
    ports:
      - "5000:3000"
    networks:
      - sportapp
    depends_on:
      postgres:
        condition: service_healthy   

  gestorentrenamientos:
    container_name: gentrenamientos
    hostname: gentrenamientos
    restart: on-failure
    build:
      context: ./gestor_entrenamientos
      dockerfile: Dockerfile
      target: prod
    environment:
      - GESTORENTRENAMIENTOS_ADDRESS=gentrenamientos
      - GESTORUSUARIOS_ADDRESS=https://my.api.mockaroo.com/v1/users
      - PATH_PUBSUB_KEY=proyecto1-experimentos-a4f693fafcec.json
      - PATH_TOPIC_ALERTAS=projects/proyecto1-experimentos/topics/alarmas
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sportapp
      - APP_PORT=3000
    ports:
      - "5001:3000"
    networks:
      - sportapp
    depends_on:
      postgres:
        condition: service_healthy

  gestorservicios:
    container_name: gservicios
    hostname: gservicios
    restart: on-failure
    build:
      context: ./gestor_servicios
      dockerfile: Dockerfile
      target: prod
    environment:
      - GESTORENTRENAMIENTOS_ADDRESS=gservicios
      - GESTORUSUARIOS_ADDRESS=https://misw-pf-grupo1-backend-gestor-usuarios-klme3r4qta-uc.a.run.app/usuarios/me
      - PATH_PUBSUB_KEY=proyecto1-experimentos-a4f693fafcec.json
      - PATH_TOPIC_MASIVAS=projects/proyecto1-experimentos/topics/notifications
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=34.136.51.44
      - DB_PORT=5432
      - DB_NAME=postgres
      - APP_PORT=3000
      - ROL_PERMITIDO=PRESTADOR
      - ROL_AGENDAR_USUARIO=Usuario
    ports:
      - "5002:3000"
    networks:
      - sportapp
    depends_on:
      postgres:
        condition: service_healthy     