###################################
# GESTOR DE ENTRENAMIENTOS
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrenamientos
  labels:
    app: entrenamientos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: entrenamientos
  template:
    metadata:
      labels:
        app: entrenamientos
    spec:
      restartPolicy: Always
      containers:
        - name: entrenamientos
          image: us-central1-docker.pkg.dev/proyecto1-experimentos/experimentos-misw4501-g1/gentrenamientos:1.0
          ports:
            - containerPort: 3000
          env:
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_NAME
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_HOST
            - name: "DB_PORT"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_PORT
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_USER
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_PASSWORD                           
            - name: "NOTIFICACIONES_PATH"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: NOTIFICACIONES_PATH     
            - name: "PATH_TOPIC_ALERTA"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: PATH_TOPIC_ALERTA                   
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: entrenamientos-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3000
    type: HTTP
    requestPath: /entrenamientos/ping
---
kind: Service
apiVersion: v1
metadata:
  name: entrenamientos-service
  annotations:
    cloud.google.com/backend-config: '{"default": "entrenamientos-config"}'
spec:
  type: NodePort
  selector:
    app: entrenamientos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31017
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaller-entrenamientos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: entrenamientos
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 40
---      
###################################
# GESTOR DE SERVICIOS
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicios
  labels:
    app: servicios
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servicios
  template:
    metadata:
      labels:
        app: servicios
    spec:
      restartPolicy: Always
      containers:
        - name: servicios
          image: us-central1-docker.pkg.dev/proyecto1-experimentos/experimentos-misw4501-g1/gservicios:1.0
          ports:
            - containerPort: 3000
          env:
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_NAME
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_HOST
            - name: "DB_PORT"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_PORT
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_USER
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_PASSWORD                             
            - name: "NOTIFICACIONES_PATH"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: NOTIFICACIONES_PATH
            - name: "PATH_TOPIC_MASIVAS"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: PATH_TOPIC_MASIVAS
          imagePullPolicy: Always  
          resources:
            requests:
              cpu: 200m                        
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: servicios-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3000
    type: HTTP
    requestPath: /servicios/ping
---
kind: Service
apiVersion: v1
metadata:
  name: servicios-service
  annotations:
    cloud.google.com/backend-config: '{"default": "servicios-config"}'
spec:
  type: NodePort
  selector:
    app: servicios
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31018
---  
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaller-servicios
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: servicios
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 40
---
